# Generated by Django 5.2.8 on 2025-11-13 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
                ('enactment_date', models.DateField(blank=True, null=True)),
                ('source_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('history_notes', models.TextField(blank=True, null=True)),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='laws.law')),
            ],
        ),
    ]
