# Generated by Django 5.2.8 on 2025-11-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='law_pdfs/'),
        ),
    ]
