# Generated by Django 5.2.8 on 2025-11-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0002_law_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='extracted_text',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
