# Generated by Django 5.2.8 on 2025-11-14 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0003_law_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='chapter_heading',
            field=models.CharField(blank=True, help_text='e.g., Chapter 1: Offences', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='part_heading',
            field=models.CharField(blank=True, help_text='e.g., PART I - PRELIMINARY', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Appendix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appendix_number', models.CharField(help_text='e.g., Appendix A', max_length=100)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField()),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appendices', to='laws.law')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_number', models.CharField(help_text='e.g., First Schedule', max_length=100)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField()),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='laws.law')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
