# Generated by Django 5.2.8 on 2025-11-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0004_section_chapter_heading_section_part_heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_title',
            field=models.CharField(blank=True, help_text='e.g., Definition', max_length=1000, null=True),
        ),
    ]
