# Generated by Django 5.2.8 on 2025-11-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0005_section_section_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='ai_prepared_text',
            field=models.TextField(blank=True, help_text='Cleaned, tagged text from the AI assistant.', null=True),
        ),
    ]
