# Generated by Django 5.2.8 on 2025-11-19 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0006_law_ai_prepared_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='law',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='section',
            name='number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='appendix',
            name='appendix_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appendix',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appendix',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='law',
            name='ai_prepared_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='law',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='law',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='law',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='law',
            name='source_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='law',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='section',
            name='chapter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='laws.chapter'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('chapter', 'number')},
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='laws.law')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='laws.part'),
        ),
        migrations.RemoveField(
            model_name='section',
            name='chapter_heading',
        ),
        migrations.RemoveField(
            model_name='section',
            name='history_notes',
        ),
        migrations.RemoveField(
            model_name='section',
            name='law',
        ),
        migrations.RemoveField(
            model_name='section',
            name='part_heading',
        ),
        migrations.RemoveField(
            model_name='section',
            name='section_number',
        ),
        migrations.RemoveField(
            model_name='section',
            name='section_title',
        ),
    ]
